apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appNameRedis }}
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.appNameRedis }}
    app: demo-app
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      name: {{ .Values.appNameRedis }}
      app: demo-app 
  template:
    metadata:
      name: {{ .Values.appNameRedis }}
      labels:
        name: {{ .Values.appNameRedis }}
        app: demo-app 
    spec:
      containers:
        - name: redis
          image: redis
          ports:  
            - containerPort: 6379
          resources:
            requests:
              memory: "16Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"

      