apiVersion: v1
kind: Service
metadata: 
  name: {{ .Values.service.nameVote }}
  namespace: {{ .Values.namespace }}
  labels: 
    name: {{ .Values.service.nameVote }}
    app: demo-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: {{ .Values.NodePort }}
  selector:
    name: {{ .Values.appNameVote }}
    app: demo-app